language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t esergienko/udemy-docker -f Dockerfile.dev .

script:
    - docker run esergienko/udemy-docker
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-udemy"
    env: "DockerUdemy-env"
    bucket_name: "elasticbeanstalk-us-east-2-996926606589"
    bucket_path: "docker-udemy"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
